---
layout: page
permalink: /presentations/
title: presentations
[//]: # (description: presentations by categories in reversed chronological order. generated by jekyll-scholar.)
nav: false
nav_order: 2
---

<div class="publications">

{% bibliography -f {{ site.scholar.bibliography }} %}

</div>
